### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by clhexftw** [PixelOS-Pixelish/official_devices#103]
## Name and Codename of the device you want to apply for 
```
Poco X3 Pro (vayu/bhima)
```

## Device Tree sources

```
https://github.com/clhexftw/android_device_xiaomi_vayu
https://github.com/clhexftw/android_kernel_xiaomi_vayu
https://github.com/clhexftw/android_vendor_xiaomi_vayu
```

## What ROM's do you maintain officially/unofficially
```
Arrowos (personal builds), elytraos (official)
```

## How long have you been building Custom ROMs
```
7-8 months
```

## Any Exceptions/special concern?
```
Ik sarthak and debain car
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
@hexcl
```

### Link to your XDA thread of unofficial build

```

```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/clhex_blog/276
```

**Comment by whyredfire** [comment]
This flag is redundant for libperf, https://github.com/clhexftw/android_device_xiaomi_vayu/blob/32df006abcc7b6a0373af9847ce69eb615566063/BoardConfig.mk#L126.

Make one XDA Thread for your unofficial release.

**Comment by clhexftw** [comment]
> This flag is redundant for libperf, https://github.com/clhexftw/android_device_xiaomi_vayu/blob/32df006abcc7b6a0373af9847ce69eb615566063/BoardConfig.mk#L126.
> 
> Make one XDA Thread for your unofficial release.

nuked that also made xda thread **https://forum.xda-developers.com/t/rom-12-1-unofficial-pixelos-aosp-stable-19-04-2022.4467493/**

**Comment by whyredfire** [comment]
Okay perfect, PM me on telegram for the rest of the procedure.
