### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by moonitime** [PixelOS-Pixelish/official_devices#112]
## Name and Codename of the device you want to apply for 
```
Redmi Note 7/7S (lavender)
```

## Device Tree sources

```
https://github.com/Mooni-s-Lab/android_device_xiaomi_lavender
https://github.com/Mooni-s-Lab/android_vendor_xiaomi_lavender
https://github.com/Mooni-s-Lab/android_kernel_xiaomi_lavender-LTO
```

## What ROM's do you maintain officially/unofficially
```
Project Kasumi (OFFICIAL) and PixelOS 
```

## How long have you been building Custom ROMs
```
6-7 Months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
moonichanwa
```

### Link to your XDA thread of unofficial build
```
https://forum.xda-developers.com/t/rom-12-1-unofficial-pixelos-aosp-stable-25-06-2022.4461405/
```

### Link to your unofficial PixelOS Build Post other than XDA
```
https://t.me/moonixupdate/107
```

**Comment by whyredfire** [comment]
![image](https://user-images.githubusercontent.com/72072109/178147530-d8da2680-85f8-4892-b5b6-0820880368ba.png)
lavender: Reject-ify!

**Comment by Seraphine3** [comment]
@whyredfire

**Comment by Seraphine3** [comment]
@Seraphine3 lol

**Comment by moonitime** [comment]
lavender: I FORGOR 💀

**Comment by Seraphine3** [comment]
@moonitime
