### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AnandSuresh02** [PixelOS-Pixelish/official_devices#114]
## Name and Codename of the device you want to apply for 
```
Asus Zenfone Max Pro M1 (X00T/X00TD)
```

## Device Tree sources

```
https://github.com/AnandSuresh02/device_asus_X00TD
https://github.com/AnandSuresh02/kernel_asus_sdm660
https://github.com/AnandSuresh02/vendor_asus_X00TD
```

## What ROM's do you maintain officially/unofficially
```
PixelOS (unofficially)
```

## How long have you been building Custom ROMs
```
About 3 months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
AnandSuresh02
```

### Link to your XDA thread of unofficial build

```
Not posted on XDA
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/ZFMaxProM1Support/70105
https://t.me/ZFMaxProM1Support/72218
```

**Comment by geek0609** [comment]
Hey @AnandSuresh02, 
Your application has been rejected since you do not qualify for our Maintainer Requirements.

**Comment by AnandSuresh02** [comment]
> Hey @AnandSuresh02, Your application has been rejected since you do not qualify for our Maintainer Requirements.

Can you please specify which requirement I violated?
