### ISSUE TITLE
New maintainer [Xiaomi Redmi 5 Rosy]

### ISSUE THREAD

**Issue by a3project** [PixelOS-Pixelish/official_devices#149]
## Name and Codename of the device you want to apply for 
```
Xiaomi Redmi 5 Rosy
```

## Device Tree sources

```
https://github.com/a3project/android_device_xiaomi_rosy
https://github.com/a3project/android_kernel_xiaomi_rosy
https://github.com/a3project/android_vendor_xiaomi_rosy
```

## What ROM's do you maintain officially/unofficially
```
PixelOS Unofficial, Project Blaze Unofficial
```

## How long have you been building Custom ROMs
```
1 Month
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
- Patch vendor/aosp/config/BoardConfigQcom.mk for detecting msm8953
- Patch build/soong/cc/compiler.go for whitelist HALs in device tree
```

### Telegram username
```
https://t.me/aepranata
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-12-1-unofficial-pixelos-aosp-rosy-11-08-2022.4479029/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/a3discussion
https://t.me/rosy_indonesia
https://t.me/rosy_global
```

**Comment by geek0609** [comment]
@a3project Hey there,
Your application is put on hold as we prepare ourselves for Android 13 releases. 

There might be changes to Guidelines and Requirements for our next version, your application will be reviewed once we restart accepting new applications.

For updates, refer our official telegram channel: https://t.me/PixelOSOfficial

**Comment by geek0609** [comment]
Hey there, 
If you are still interested, read our [docs](https://blog.pixelos.net/docs/JoinTheTeam) and reapply with updated details
