### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by a3project** [PixelOS-Pixelish/official_devices#158]
## Name and Codename of the device you want to apply for 
```
Redmi 5 (Rosy)
```

## Device Tree sources

```
https://github.com/a3project/android_device_xiaomi_rosy
https://github.com/a3project/android_kernel_xiaomi_rosy
https://github.com/a3project/android_vendor_xiaomi_rosy
```

## What ROM's do you maintain officially/unofficially
```
PixelOS
```

## How long have you been building Custom ROMs
```
2 Months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
build/soong/cc/compiler.go
- Add 'device' in 'allowedManualInterfacePaths'

vendor/aosp/config/BoardConfigQcom.mk
- Remove msm8953 on UM_3_18_FAMILY
- Remove
ifeq ($(TARGET_USES_UM_4_19),true)
    QSSI_SUPPORTED_PLATFORMS += $(TARGET_BOARD_PLATFORM)
end
- Add
ifeq (,$(TARGET_ENFORCES_QSSI))
	UM_3_18_FAMILY += msm8953
else
	QSSI_SUPPORTED_PLATFORMS += msm8953
endif
```

### Telegram username
```
https://t.me/aepranata
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-13-unofficial-pixelos-aosp-stable-2022-09-25.4498241/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/a3archive
```

**Comment by whyredfire** [comment]
![image](https://user-images.githubusercontent.com/72072109/197521115-eea3b56b-a477-45d7-b165-e757f8a1d80e.png)

**Comment by a3project** [comment]
I've change to new account. I must reapply again?

**Comment by geek0609** [comment]
@a3project If you feel your new application will be valid
And if you've read our maintainer policies https://blog.pixelos.net/docs/JoinTheTeam

Feel free to reapply
