### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ok-ano0s** [PixelOS-Pixelish/official_devices#17]
## Name and Codename of the device you want to apply for 
```
Realme C2 (RMX1941)
```

## Device Tree sources

```
https://github.com/ok-ano0s/device_realme_RMX1941
https://github.com/ok-ano0s/android_vendor_realme_RMX1941
Realme haven't released kernel source for q base.
```

## What ROM's do you maintain officially/unofficially
```
Project Sakura [OFFICIAL] , CipherOS [OFFICIAL]
```

## How long have you been building Custom ROMs
```
10 months
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@ok_ano0s
```

### Link to your unofficial PixelOS Build Post

```
Unfortunately, I haven't released a unofficial build.
```

### GitHub username
```
@ok-ano0s 
```

**Comment by bheatleyyy** [comment]
@sajidshahriar72543
