### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ok-ano0s** [PixelOS-Pixelish/official_devices#18]
## Name and Codename of the device you want to apply for 
```
Realme C3 / Narzo 10A (realme Monet or RMX2020)
```

## Device Tree sources

```
https://github.com/ok-ano0s/device_realme_RMX2020
https://github.com/sarthakroy2002/vendor_realme_RMX2020
https://github.com/sarthakroy2002/kernel_realme_RMX2020
```

## What ROM's do you maintain officially/unofficially
```
Project Sakura [OFFICIAL] , CipherOS [OFFICIAL]
```

## How long have you been building Custom ROMs
```
10 months
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@ok_ano0s , @zidaneharith
```

### Link to your unofficial PixelOS Build Post

```
Unfortunately, I haven't posted a build publically yet.
```

### GitHub username
```
@ok-ano0s , @zidaneharith
```

**Comment by whyredfire** [comment]
@ok-ano0s um
