### ISSUE TITLE
Generic System img 

### ISSUE THREAD

**Issue by zainullahk** [PixelOS-Pixelish/official_devices#19]
## Name and Codename of the device you want to apply for 
```
Your device name (Your device codename)
```

## Device Tree sources

```
https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```

## What ROM's do you maintain officially/unofficially
```
Insert here
```

## How long have you been building Custom ROMs
```
Insert here
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
Your Telegram username
```

### Link to your unofficial PixelOS Build Post

```
Link to where you have posted your build publically.
```

### GitHub username
```
Your GitHub username
```

**Comment by sajidshahriar72543** [comment]
@zainullahk

**Comment by zainullahk** [comment]
sorry i clicked enter bymistake

**Comment by sajidshahriar72543** [comment]
@sajidshahriar72543
