### ISSUE TITLE
Generic System Image PixelOS

### ISSUE THREAD

**Issue by zainullahk** [PixelOS-Pixelish/official_devices#20]
## Name and Codename of the device you want to apply for 
```
Your device name (Your device codename)
```

## Device Tree sources

```
N/A 
```

## What ROM's do you maintain officially/unofficially
```
i maintain dotos and pe for a71 (they are gsi but with bug fixes and workarounds etc)
```

## How long have you been building Custom ROMs
```
few months 
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
rixhant
```

### Link to your unofficial PixelOS Build Post

```
https://github.com/Zainullahorg/treble_build_pe
(note the build is ready just not uploaded yet )
```

### GitHub username
```
zainullahk1234
```

**Comment by whyredfire** [comment]
Hello!
As per our maintainer requirements https://github.com/PixelOS-Pixelish/official_devices/blob/twelve/docs/maintainerreq.md, you must release your GSI build before applying. Other than that, your repository have poor commit titles and several unnecessary commits, which again violates our requirements.
