### ISSUE TITLE
Poco x3 pro maintainer (old maintainer has sold x3 pro)

### ISSUE THREAD

**Issue by zainullahk** [PixelOS-Pixelish/official_devices#22]
## Name and Codename of the device you want to apply for 
```
Vayu
```

## Device Tree sources

```
https://github.com/zainullahk/device_xiaomi_vayu
https://github.com/zainullahk/kernel_sm8150
https://github.com/zainullahk/vendor_xiaomi_vayu
```

## What ROM's do you maintain officially/unofficially
```
Pixel experience, Dotos (note that these are just modified gsi versions but i spend a lot of time on)
```

## How long have you been building Custom ROMs
```
4-5 months now
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
zain1019018
```

### Link to your unofficial PixelOS Build Post

```
shorturl.at/ltQ29 (note this is just a download link actual xda post i will make once tommorow or i will wait until it is official so it can come with ota 
```

### GitHub username
```
Zainullahk1234
```

**Comment by zainullahk** [comment]
i have tested it properly

**Comment by zainullahk** [comment]
@geek0609  why rejected?

**Comment by geek0609** [comment]
We're rejecting you for the following reasons :

- You've no contribution to your Device Trees
- You've not released a build, instead of that you've given us a build (like what do we do with it)
- You don't satisfy our maintainer requirements as listed [here](https://github.com/PixelOS-Pixelish/official_devices/blob/twelve/docs/maintainerreq.md#to-become-an-official-maintainer-of-pixelos)

**Comment by zainullahk** [comment]
nvm the link was broken 
#23  link is fine

**Comment by geek0609** [comment]
> You've not released a build, instead of that you've given us a build (like what do we do with it) ok ill upload it to xda but the tree part shouldnt be an issue right?

We have our requirements of who is eligible to maintain officially. You can continue your unofficial build if your current trees are perfect and don't need any changes or contributions.

**Comment by zainullahk** [comment]
> > You've not released a build, instead of that you've given us a build (like what do we do with it) ok ill upload it to xda but the tree part shouldnt be an issue right?
> 
> We have our requirements of who is eligible to maintain officially. You can continue your unofficial build if your current trees are perfect and don't need any changes or contributions.

why is that a rule?
 so i should just add random lines to the build so it can be official?

**Comment by zainullahk** [comment]
how many commits do i need to get in?
cause  i plan to adjust it depending on  how it goes (not random lines but actually changin stuff)

**Comment by zainullahk** [comment]
@geek0609

**Comment by zainullahk** [comment]
ill change the system prop tommorow to add some stuff and will try to make it official again

**Comment by ArixElo** [comment]
> ill change a few things tommorowand will try to make it official again

**How long have you been building Custom ROMs**
_Yes_

**Comment by zainullahk** [comment]
> > ill change a few things tommorowand will try to make it official again
> 
> **How long have you been building Custom ROMs** _Yes_

?
im gonna change the readme only lol
there is nothing to change  the rules by PixelOS team is dumb
