### ISSUE TITLE
Sweet new maintaniership request

### ISSUE THREAD

**Issue by Zestify24** [PixelOS-Pixelish/official_devices#24]
## Name and Codename of the device you want to apply for 
```
Redmi Note 10 Pro/Pro Max (sweet/sweetin)
```

## Device Tree sources

```
https://github.com/Zestify24/aosp_device_xiaomi_sweet Pos-12
https://github.com/vantoman/kernel_xiaomi_sm6150 courbet
https://github.com/Zestify24/vendor_xiaomi_sweet 12-OSS
```

## What ROM's do you maintain officially/unofficially
```
ppui , Cafex Both officially , Aospa unofficially
```

## How long have you been building Custom ROMs
```
8 months 
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@ZeSyI
```

### Link to your unofficial PixelOS Build Post

```
https://t.me/RedmiNote10ProDiscussion/791863
```

### GitHub username
```
Zestify24
```

**Comment by bheatleyyy** [comment]
First of all, you have stated that you have been building custom roms for 8 months, but that does't seems to be true. Second, your device tree seems to be messed up and we would like to see a more cleaner tree. Moreover, the vendor tree link that you linked in your application seems to be private/doesn't exist. We're closing your application for now as we also have an existing maintainer for sweet as he prefers to do it without any co-maintainers and we dont need 2 builds for a device...

**Comment by Zestify24** [comment]
First of all 8 months is true second idt my device tree is messed up in any manner and third maybe wrong link fourth fine.

**Comment by bheatleyyy** [comment]
> First of all 8 months is true second idt my device tree is messed up in any manner and third maybe wrong link fourth fine. Plus show me where my device tree is messed up thanks .

Hello there. 
1. Regarding your claim of  building for "8 months", we have not found any evidence supporting your statement. Your GitHub account was made on November 4th 2021, and the first ROM that was compiled by you was released on the 13th November 2021[(ref)](https://t.me/RedmiNote10ProChannel/722). This is barely 4 months.
2. When it comes to your tree, after our review we found quite a number of issues with it. One of the major ones was wondering what are you actually building, is it QTI power HAL or libperfmgr. After looking at your [tree, the last 4 commits here,](https://github.com/Zestify24/aosp_device_xiaomi_sweet/commits/b44230a155159ded2907e8ffe561469b2d347ca6) it looks as if you've confused the both of them and expect one of them to work.
3. You should have checked the links to see if the repos were correct before applying.

**Comment by Zestify24** [comment]
1 Ok maybe wrong math there 
2 I'm not confused with anything I'm using qti perf d with the lib perf mgr it works fine boosts performance quite a lot I'm anything but confused 
3 that's true
