### ISSUE TITLE
Poco x3 pro maintainer (extensively tested everything for bugs)

### ISSUE THREAD

**Issue by zainullahk** [PixelOS-Pixelish/official_devices#25]
## Name and Codename of the device you want to apply for 
```
Vayu
```

## Device Tree sources

```
https://github.com/zainullahk/device_xiaomi_vayu
https://github.com/zainullahk/kernel_sm8150
https://github.com/zainullahk/vendor_xiaomi_vayu
```

## What ROM's do you maintain officially/unofficially
```
Dotos 5.2.1 Generic System image 
```

## How long have you been building Custom ROMs
```
4-5 months now
```

## Any Exceptions/special concern?
```
i have changed trees to my suiting (no i didnt just change readme)
```

### Telegram username
```
zain1019018
```

### Link to your unofficial PixelOS Build Post

```
[Here](https://forum.xda-developers.com/t/pixelos-for-vayu-unofficial.4409463/#post-86503121)
```

### GitHub username
```
Zainullahk1234
```

**Comment by zainullahk** [comment]
i tested everything  and found only 1 bug which is ambient display (which didnt work on old maintainer build either)

**Comment by SashaMcC** [comment]
Hello, as previously mentioned in the last post* we do not believe you would be a good fit for the project. This has further been exemplified by your opinions voiced in the Pixel OS chat yesterday**. As such, your application has been declined as will continue to happen in future

*https://github.com/PixelOS-Pixelish/official_devices/issues/22#issuecomment-1052558351

**
"forget it
Pixelos good rom
pixelos rule makers=suck

anyway idc

sanjeevstunner is working on it

so i dont care anymor"

**Comment by zainullahk** [comment]
i ddint say such things @SashaMcC 
please send a screenshot
also did the id zain1019018 say it 
as zain1019018 is my main account

**Comment by zainullahk** [comment]
also why would i not be a good fit 
im sorry about calling the project  rule makers dumb on github (i love this project)
but i didnt  say pixelos rule makers= suck 
also why am i "not fit"
i made the rom and i will update it forever
right now pixelos for vayuhas no maintainers and your rejecting the only one actually wanting to apply

@SashaMcC

**Comment by syhhw** [comment]
@zainullahk bhai wtf
