### ISSUE TITLE
X3  pro maintainer (read exceptions/special concern)

### ISSUE THREAD

**Issue by zainullahk** [PixelOS-Pixelish/official_devices#26]
## Name and Codename of the device you want to apply for 
```
Vayu
```

## Device Tree sources

```
https://github.com/zainullahk/device_xiaomi_vayu
https://github.com/zainullahk/kernel_sm8150
https://github.com/zainullahk/vendor_xiaomi_vayu
```

## What ROM's do you maintain officially/unofficially
```
Dotos 5.2.1 Generic System image 
```

## How long have you been building Custom ROMs
```
4-5 months now
```

## Any Exceptions/special concern?
```
i have changed trees to my suiting (no i didnt just change readme) 
also im sorry for calling rule makers dumb but some other accusations of what i have said in some "chat" i have not (the only acc i use on tg is zain1019018 )
```

### Telegram username
```
zain1019018
```

### Link to your unofficial PixelOS Build Post

```
[Here](https://forum.xda-developers.com/t/pixelos-for-vayu-unofficial.4409463/#post-86503121)
```

### GitHub username
```
Zainullahk1234
```

**Comment by whyredfire** [comment]
Let me get this straight, this is the third time you've opened an issue here.
* Building `Dotos 5.2.1 Generic System image` is different from actually building entire roms.
* zainullahk/device_xiaomi_vayu@36ea373d6dab6a7213c39cd56e30e7ddf5195f66 and zainullahk/device_xiaomi_vayu@13db4dc1bdd79b9ae79c1d1ebce64c55e7c59752 are useless commits with improper commit titles which translates to your 'zero' experience with github and managing device trees.
* Telegram account with username `zain1019018` doesn't exist at the time of writing.
* We even digged into your github account for finding anything that can show your previous previous work experience either with custom roms or with any sort of development and often ended up with baseless pull requests.

You DO NOT quality the minimum requirements of being a maintainer at PixelOS.
