### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Alone0316** [PixelOS-Pixelish/official_devices#3]
## Name and Codename of the device you want to apply for 
```
Redmi Note 4/4x (mido)
```

## Device Tree sources

```
https://github.com/Alone0316/device_xiaomi_mido/tree/PixelOS-Pixelish
https://github.com/Alone0316/kernel_mido
https://github.com/Alone0316/vendor_xiaomi_mido
```

## What ROM's do you maintain officially/unofficially
```
Project Arcana and CipherOS (officially)
```

## How long have you been building Custom ROMs
```
3 months
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@Alone0316
```

### Link to your unofficial PixelOS Build Post

```
https://t.me/rn4dl/1833
```

### GitHub username
```
https://github.com/Alone0316
```

**Comment by whyredfire** [comment]
Everything looks fine.
Revert Alone0316/device_xiaomi_mido/commit/37635a47d02214dc0a014e92c038f7043935f51c as the flicker/glitch bug was fixed in r18 merge.

**Comment by Alone0316** [comment]
> Everything looks fine. Revert [Alone0316/device_xiaomi_mido@37635a4](https://github.com/Alone0316/device_xiaomi_mido/commit/37635a47d02214dc0a014e92c038f7043935f51c) as the flicker/glitch bug was fixed in r18 merge.

Ok i will revert it back

**Comment by geek0609** [comment]
@Alone0316 please make a pull request to [PixelOS-Pixelish/official_devices](https://github.com/PixelOS-Pixelish/official_devices) adding ```mido.json``` to API/devices. You can use the README and ```mojito.json``` as reference. 

You can set the variables ```public_download``` and ```private_download_tag```  to ```""```  (two double quotes with nothing between them)
