### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RayapKun** [PixelOS-Pixelish/official_devices#35]
## Name and Codename of the device you want to apply for 
```
Poco M3 x Redmi 9T (Juice)
```

## Device Tree sources

```
https://github.com/RayapKun/device_xiaomi_juice
https://github.com/RayapKun/kernel_xiaomi_juice
https://github.com/RayapKun/vendor_xiaomi_juice
```

## What ROM's do you maintain officially/unofficially
```
Project Arcana [Official]
```

## How long have you been building Custom ROMs
```
6 Month
```

## Any Exceptions/special concern?
```
No
```

### Telegram username
```
@whyyraku
```

### Link to your unofficial PixelOS Build Post

```
https://forum.xda-developers.com/t/rom-android-12-poco-m3-redmi-9t-redmi-9-power-redmi-note-9-4g-juice-pixelos-unofficial-14-02-2022.4426729/
```

### GitHub username
```
RayapKun
```

**Comment by cyberknight777** [comment]
@RayapKun Me wen

**Comment by whyredfire** [comment]
Please make an XDA thread and update us with the same.

**Comment by RayapKun** [comment]
> Please make an XDA thread and update us with the same.

updated link to xda thread

**Comment by whyredfire** [comment]
Make a pull request in the same repo for your device, target team.json, devices.json and devices/juice.json. Once done, you can PM me on telegram.
