### ISSUE TITLE
New maintainer for moon

### ISSUE THREAD

**Issue by Imshubh69** [PixelOS-Pixelish/official_devices#39]
## Name and Codename of the device you want to apply for 
```
Realme Narzo 30A,Realme Narzo 20 and Realme 7i eu unified as codename moon
```

## Device Tree sources

```
https://github.com/Imshubh69/device_realme_moon
https://github.com/Imshubh69/kernel_realme_moon
https://github.com/Imshubh69/vendor_realme_moon
```

## What ROM's do you maintain officially/unofficially
```
Pixelexperience unofficially
```

## How long have you been building Custom ROMs
```
4 months
```

## Any Exceptions/special concern?
```
I know anoos
```

### Telegram username
```
shubhbruh
```

### Link to your unofficial PixelOS Build Post

```
Never released sadly
```

### GitHub username
```
imshubh69
```

**Comment by kardebayan** [comment]
@Imshubh69 Die

**Comment by sushmit1** [comment]
Ong

**Comment by geek0609** [comment]
Hey @Imshubh69,
You have not released an unofficial build that we mandate as per our requirements. You will be put on hold until then.

**Comment by Imshubh69** [comment]
> Hey @Imshubh69, You have not released an unofficial build that we mandate as per our requirements. You will be put on hold until then.

Ok i will release unofficial build in 1-2 days
