### ISSUE TITLE
New maintainer for RMX1971

### ISSUE THREAD

**Issue by eun0115** [PixelOS-Pixelish/official_devices#40]
## Name and Codename of the device you want to apply for 
```
realme 5 Pro (RMX1971)
```

## Device Tree sources

```
https://github.com/eun0115/android_device_realme_RMX1971
https://github.com/eun0115/android_device_realme_sdm710-common
https://github.com/eun0115/android_device_realme_sdm710
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_realme_RMX1971
https://github.com/eun0115/vendor_realme_sdm710-common
```

## What ROM's do you maintain officially/unofficially
```
Derpfest (Officially)
```

## How long have you been building Custom ROMs
```
10 months
```

## Any Exceptions/special concern?
```
i know anoos, sarthak, and kardebayan
```

### Telegram username
```
eun0115
```

### Link to your unofficial PixelOS Build Post

```
never released sadly
```

### GitHub username
```
github.com/eun0115
```

**Comment by geek0609** [comment]
Hey @eun0115,
You have not released an unofficial build that we mandate as per our requirements. You will be put on hold then.

**Comment by geek0609** [comment]
Hey @eun0115,
I will be closing this application due to inactivity. Feel free to create a new one if you wish to.
