### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by wzwzx** [PixelOS-Pixelish/official_devices#44]
## Name and Codename of the device you want to apply for 
```
Redmi Note 8 Pro[begonia/begonian]
```

## Device Tree sources

```
https://github.com/wzwzx/device_xiaomi_begonia-new
https://github.com/wzwzx/vendor_xiaomi_begonia-new
https://github.com/PixelExperience-Devices/kernel_xiaomi_begonia
```

## What ROM's do you maintain officially/unofficially
```
exTHmUI(Before) Nortical-UI [officially]
MikuUI [unofficially]
```

## How long have you been building Custom ROMs
```
10 months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
wzwzx_wz
```

### Link to your XDA thread of unofficial build

```
I didn't use xda before.
```

### Link to your unofficial PixelOS Build Post other than XDA

```
No public release yet.
```

**Comment by geek0609** [comment]
@wzwzx Hey there,

I noticed few things

1. You've not released an unofficial update yet, we mandate an unofficial build before applying (unless exceptions are made)
2. We mandate that you make an XDA thread, you've clearly read it and ignored it
3. You lack contributions to Device/Vendor/Kernel trees

You'll be rejected as of now, however feel free to correct the above mentioned then re-applying later.
