### ISSUE TITLE
New maintainer For Lavender

### ISSUE THREAD

**Issue by inferno964** [PixelOS-Pixelish/official_devices#46]
## Name and Codename of the device you want to apply for 
```
Xiaomi Redmi Note 7 (Lavender)
```

## Device Tree sources

```
https://github.com/inferno964/device_xiaomi_lavender
https://github.com/inferno964/device_xiaomi_sdm660-common
https://github.com/inferno964/vendor_xiaomi_lavender
https://github.com/inferno964/vendor_xiaomi_sdm660-common
https://github.com/inferno964/android_kernel_xiaomi_sdm660
```

## What ROM's do you maintain officially/unofficially
```
AospExtended Officially & PixelExp Unofficially
```

## How long have you been building Custom ROMs
```
6-7 months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
inferno964
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-12-1-lavender-unofficial-pixelos-aosp-stable-08-04-22.4428535/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://drive.google.com/file/d/19kT25IBHvAdvRi-oP5AIiPMDU6izgIbx/view?usp=drivesdk
```

**Comment by geek0609** [comment]
Hey there @inferno964,

We reviewed your trees, something we felt off was that you had picked 5 to 6 pages of commits in one day, before those the last commit was https://github.com/inferno964/device_xiaomi_sdm660-common/commit/ca15d901e44843831aa07c5ae7f04356d3200fa8 about a year ago in April 2021, could you explain it?

**Comment by inferno964** [comment]
> Hey there @inferno964,
> 
> We reviewed your trees, something we felt off was that you had picked 5 to 6 pages of commits in one day, before those the last commit was https://github.com/inferno964/device_xiaomi_sdm660-common/commit/ca15d901e44843831aa07c5ae7f04356d3200fa8 about a year ago in April 2021, could you explain it?

The common tree was rebased.
If you wanna check my commit history then look at the lavender specific tree.

**Comment by inferno964** [comment]
Also , the common device tree will be rebased again in the future.

**Comment by spkal01** [comment]
@inferno964 ah that guy

**Comment by whyredfire** [comment]
@inferno964 Why was it rebased?

**Comment by inferno964** [comment]
> @inferno964 Why was it rebased?

Switched from hmp to eas

**Comment by sarthakroy2002** [comment]
> > @inferno964 Why was it rebased?
> 
> Switched from hmp to eas

I would like to know why even changing scheduler needs a entire rebase..isnt it just few commits?

**Comment by inferno964** [comment]
Nvm me buildbot forever.

**Comment by inferno964** [comment]
Thanks everyone for your time.

**Comment by Twel12** [comment]
why get so emotional :/

**Comment by inferno964** [comment]
> why get so emotional :/
> 

I'm not being emotional. I'm curious why are they questioning me like that.
Maybe I don't deserve to be a maintainer in thier team.

**Comment by basamaryan** [comment]
@inferno964 It is questioned because you applied to maintain the ROM and attached your device sources for review.

**Comment by inferno964** [comment]
> @inferno964 It is questioned because you applied to maintain the ROM and attached your device sources for review.

Why new reviewer each time ? I was interested to maintain that's why I applied. And for commit history I said check the lavender tree.

**Comment by geek0609** [comment]
@inferno964 It was just a review process and that's how I think a review should be done, and moreover we just asked for an explanation for what you did.

**Comment by inferno964** [comment]
https://github.com/inferno964/platform_device_xiaomi_lavender

Look at this tree just for 2 mins.

**Comment by inferno964** [comment]
There was schedular change and caf checkouts to media gps and other things that's why I rebased. That's it.

**Comment by geek0609** [comment]
> https://github.com/inferno964/platform_device_xiaomi_lavender
> 
> Look at this tree just for 2 mins.

It's not about looking at that tree, what we asked was different and I don't think us asking what you did is invalid

**Comment by vansh123456** [comment]
@Twel12 Bsdk hai kya?

**Comment by whyredfire** [comment]
> https://github.com/inferno964/platform_device_xiaomi_lavender
> 
> Look at this tree just for 2 mins.

does that tree even exist?

**Comment by inferno964** [comment]
> > https://github.com/inferno964/platform_device_xiaomi_lavender
> > 
> > Look at this tree just for 2 mins.
> 
> does that tree even exist?

That was my own tree bringup , made it private now like earlier. Shared that only for 5 mins so that you all can see my commits.

**Comment by whyredfire** [comment]
> > > https://github.com/inferno964/platform_device_xiaomi_lavender
> > > Look at this tree just for 2 mins.
> > 
> > 
> > does that tree even exist?
> 
> That was my own tree bringup , made it private now like earlier. Shared that only for 5 mins so that you all can see my commits.
um, sure but what do you have to say about your kanged kernel?

**Comment by whyredfire** [comment]
We're rejecting your application for the following reasons.

- Lack of proper commit history on common tree
- Kanged kernel (atleast fork it properly before rebranding it)

Furthermore, you closed your application twice by yourself without any notice.

**Comment by inferno964** [comment]
> We're rejecting your application for the following reasons.
> 
> - Lack of proper commit history on common tree
> - Kanged kernel (atleast fork it properly before rebranding it)
> 
> Furthermore, you closed your application twice by yourself without any notice.

Will reapply when I gain proper knowledge.
