### ISSUE TITLE
New maintainer for Toco

### ISSUE THREAD

**Issue by AndroidHQ254** [PixelOS-Pixelish/official_devices#55]
## Name and Codename of the device you want to apply for 
```
Xiaomi Mi Note 10 Lite (toco)
```

## Device Tree sources

```
https://github.com/AndroidHQ254/android_device_xiaomi_toco-po
https://github.com/AndroidHQ254/device_xiaomi_sm6150-common
https://github.com/vantoman/kernel_xiaomi_sm6150/tree/12.1
https://github.com/AndroidHQ254/vendor_xiaomi/tree/wfd
```

## What ROM's do you maintain officially/unofficially
```
Official (HavocOS, DotOS, Project Elixir, DerpFest)... Unofficial (CherishOS, EvolutionX, PixelExperience...
```

## How long have you been building Custom ROMs
```
For over a year
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
DennisMurimiWachira
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-12-1-toco-unofficial-pixelos.4439221/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/ahq254news/523
```

**Comment by geek0609** [comment]
@AndroidHQ254 Hey there, do you actively maintain all the mentioned ROMs (HavocOS, DotOS, Project Elixir, DerpFest, CherishOS, EvolutionX, PixelExperience) ?

**Comment by AndroidHQ254** [comment]
> @AndroidHQ254 Hey there, do you actively maintain all the mentioned ROMs (HavocOS, DotOS, Project Elixir, DerpFest, CherishOS, EvolutionX, PixelExperience) ?

I have sorted out the rom list... The official ones are the ones I maintain actively. The rest I do unofficial builds when the community requests

**Comment by whyredfire** [comment]
@AndroidHQ254 Which ones are official out of those?

**Comment by AndroidHQ254** [comment]
> @AndroidHQ254 Which ones are official out of those?

Check in the main post. I have made an edit already

**Comment by whyredfire** [comment]
@AndroidHQ254 Do you have plans on taking more official roms in future?

**Comment by AndroidHQ254** [comment]
> @AndroidHQ254 Do you have plans on taking more official roms in future?

Nope. This is my max one

**Comment by whyredfire** [comment]
@AndroidHQ254 Since you're the only one who's building for toco, we'll make an exception for you.

Pm me on tg '@whyredfire' for joining the team.
