### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by OmarAlCoptan** [PixelOS-Pixelish/official_devices#6]
## Name and Codename of the device you want to apply for 
```
Redmi note 7 (Lavender)
```

## Device Tree sources

```
https://github.com/OmarAlCoptan/device_xiaomi_lavender
https://github.com/OmarAlCoptan/vendor_xiaomi_lavender
https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
https://github.com/OmarAlCoptan/vendor_xiaomi_sdm660-common
https://github.com/stormbreaker-project/kernel_xiaomi_lavender/tree/qti-oldcam-eas

```

## What ROM's do you maintain officially/unofficially
```
PixelOS unofficial
PE unofficial
VoltageOS +Streak(didn't publish)
```

## How long have you been building Custom ROMs
```
3-4 months
```

## Any Exceptions/special concern?
```
Bro now I have an enough git knowledge , most of the things needed in building such as pushing and commiting , so bro pls unblock and let's talk 
and at last I swear I didn't google anything and everyday I learn more than the day before. and thanks for listening for me , so pls give me a chance bro
```

### Telegram username
```
@AlCoptan99
```

### Link to your unofficial PixelOS Build Post

```
https://t.me/RedmiNote7Updates/6561
```

### GitHub username
```
https://github.com/OmarAlCoptan
```

**Comment by geek0609** [comment]
Your previous application was closed with a label given as "invalid" have you gone through to check why was it?
I would close this again, but if I did, I would get another invalid application which I have to review

1. **Where are the trees?** : You have applied for PixelOS, your trees have no bring-up/changes for PixelOS. You only have a bring-up for ```VoltageOS``` on your only branch named ```12``` OmarAlCoptan/device_xiaomi_lavender@a9aca11bf3aa6527822dbb7edda7f970c8563cbe 

2. **Your contributions**: In the trees, which you had sent me, you had like 2 commits, one was Voltage bring-up and one revert commit OmarAlCoptan/vendor_xiaomi_sdm660-common@a45e3aaa3747ef859525da9435362ee7329364a4 .
