### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by RahulGorai0206** [PixelOS-Pixelish/official_devices#61]
## Name and Codename of the device you want to apply for 
```
Realme 6/6i (RM6785)
```

## Device Tree sources

```
https://github.com/RahulGorai0206/device_realme_RM6785
https://github.com/anupamroy777/kernel_realme_RM6785
https://github.com/RahulGorai0206/vendor_realme_RM6785
```

## What ROM's do you maintain officially/unofficially
```
None
```

## How long have you been building Custom ROMs
```
6 Months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
Yes
Replaced Some Framework
```

### Telegram username
```
RahulGorai
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-12-1-unofficial-pixelos-aosp-rm6785-27-04-2022.4438387/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/RM6785/1755
```

**Comment by whyredfire** [comment]
Did you read the minimum maintainership requirements properly?

**Comment by RahulGorai0206** [comment]
> Hey @RahulGorai0206, I will be closing your form due to inactivity, feel free to create a new one should you wish to reapply.

sir I read the minimum  maintainership requirements but what's the issue?
