### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by aanneion** [PixelOS-Pixelish/official_devices#62]
## Name and Codename of the device you want to apply for 
```
Realme 5/5i/5s/NFC (r5x)
```

## Device Tree sources

```
https://github.com/aanneion/device_realme_r5x
https://github.com/aanneion/kernel_realme_r5x
https://github.com/aanneion/vendor_realme_r5x
```

## What ROM's do you maintain officially/unofficially
```
PixelOS (Unofficially)
```

## How long have you been building Custom ROMs
```
5 Months
```

## Any Exceptions/special concern?
```
No
```

## List of changes/patches applied to source, if any
```
No
```

### Telegram username
```
aanNEION
```

### Link to your XDA thread of unofficial build

```
https://forum.xda-developers.com/t/rom-oss-12-1-pixelos-unofficial-realme-5-5i-5s-nfc-5-may-2022.4426103/
```

### Link to your unofficial PixelOS Build Post other than XDA

```
https://t.me/rmx_1911
```

**Comment by whyredfire** [comment]
Hi, while we were reviewing your trees, we couldn't see much of what we would consider a reasonable experience/knowledge.
You can apply again in the future whenever you've gained more experience.
